apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfset-nginx
  labels:
    app: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: sf-set-container
        image: nginx
        ports:
        - containerPort: 8086


