apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
  - name: pod-pvc-claim
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-persistent-volume-claim

