name: kubectl
version: 1.31.4
summary: kubectl controls the Kubernetes cluster manager.
description: |
  kubectl is a command line interface for running commands against Kubernetes
  clusters.
grade: stable
confinement: classic

base: core20


apps:
  kubectl:
    command: kubectl

parts:
  kubectl:
    source: .
    source-type: local
    plugin: dump
    build-snaps:
      - go/1.22/stable
    build-packages:
      - make
      - mercurial
      - git
      - rsync
    build-attributes: [no-patchelf]
    override-build: |
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      mkdir -p $GOPATH

      KUBEREPO="github.com/kubernetes/kubernetes"
      rm -rf "$GOPATH/src/$KUBEREPO"
      git clone "https://$KUBEREPO" --branch v1.31.4 --depth 1 "$GOPATH/src/$KUBEREPO"

      cd $GOPATH/src/$KUBEREPO

      
      export FORCE_HOST_GO=y
      make clean && make WHAT=cmd/kubectl
      cd $SNAPCRAFT_PART_INSTALL
      cp $GOPATH/src/$KUBEREPO/_output/bin/kubectl .

      snapcraftctl build
