apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: kk
  namespace: rest
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: demo
            port:
              number: 9090
        path: /demo1/
        pathType: Prefix
status:
  loadBalancer: {}
