apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"run":"demo1"},"name":"initial-pod","namespace":"default"},"spec":{"containers":[{"image":"hello-world","name":"demo1","resources":{}}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always"},"status":{}}
  creationTimestamp: "2025-01-05T12:53:19Z"
  labels:
    run: demo1
  name: initial-pod
  namespace: default
  resourceVersion: "12356"
  uid: 3ce5f558-f8ad-4adc-87bd-57b2733bed4d
spec:
  containers:
  - image: kalyankumar1996/projectdemo2
    imagePullPolicy: Always
    name: demo1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8vzgq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-8vzgq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-01-05T12:53:21Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-01-05T12:53:19Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-01-05T12:53:19Z"
    message: 'containers with unready status: [demo1]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-01-05T12:53:19Z"
    message: 'containers with unready status: [demo1]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-01-05T12:53:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://af27f05525417bae2bef209d4448b507bb070b41037f30ab8e3a8da1a17c109b
    image: hello-world:latest
    imageID: docker-pullable://hello-world@sha256:5b3cc85e16e3058003c13b7821318369dad01dac3dbb877aac3c28182255c724
    lastState:
      terminated:
        containerID: docker://af27f05525417bae2bef209d4448b507bb070b41037f30ab8e3a8da1a17c109b
        exitCode: 0
        finishedAt: "2025-01-05T13:08:59Z"
        reason: Completed
        startedAt: "2025-01-05T13:08:59Z"
    name: demo1
    ready: false
    restartCount: 8
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=demo1 pod=initial-pod_default(3ce5f558-f8ad-4adc-87bd-57b2733bed4d)
        reason: CrashLoopBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8vzgq
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  phase: Running
  podIP: 10.244.0.7
  podIPs:
  - ip: 10.244.0.7
  qosClass: BestEffort
  startTime: "2025-01-05T12:53:19Z"
