apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: docimage
  name: docimage
  namespace: ns1
spec:
  containers:
  - image: kalyankumar1996/projectdemo2
    name: docimage
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

